t = 0:pi/8:2*pi;
w0 = 1;
s = sin(w0*t);
n = length(t);
I = eye(n,n);
A = circshift(I,1);
[V,J] = jordan(A);
F = inv(V);
shat = F*s';
 figure;subplot(1,2,1);
 stem(s);grid on;
 xlabel('nodes');
 ylabel('Signal Value');
 title('Graph Signal');
 subplot(1,2,2);
stem(imag(shat));grid on;
 xlabel('nodes');
 ylabel('GFT coefficients');
 title('Graph Fourier Transform');